# Big Data Infrastructure Project

In diesem Projekt werden wir uns mit den Grundlagen der Durchführung von Data-Science-Projekten mit dem Fokus auf  Big Data. Besonders im Mittelpunkt stehen infrastrukturelle Herausforderungen, die bei der Arbeit mit großen Datenmengen auftreten. Ziel ist es, die notwendigen Methoden anzuwenden und eine passende Infrastruktur zu organisieren, um Daten zu verarbeiten und zu analysieren. 

**Projektablauf:**
1. Wählen Sie ein Thema, das Sie interessiert.
2. Beschaffen Sie sich die notwendigen Daten, die anschließend verarbeitet werden müssen (z.B. fertige Datensätze oder Zugang zu Daten über APIs).
3. Analysieren Sie die Daten.
4. Präsentieren und visualisieren Sie Ihre Ergebnisse.

**Projektgruppe:**
- Blazevic Ivan
- Prager Lukas
- Sidi Mammar Omar
- Zelimchanow Chamberg

## Thema: Zusammenhang der Lebenserwartung mit anderen Faktoren

Im Rahmen dieses Projekts wird die **Lebenserwartung** als zentrales Thema untersucht. Dabei sollen Zusammenhänge zwischen der Lebenserwartung und verschiedenen sozialen, wirtschaftlichen sowie gesundheitlichen Faktoren beleuchtet werden. Die verwendeten Daten beinhalten verschiedene Variablen, die Einfluss auf die Lebenserwartung haben könnten, wie zum Beispiel das **Bruttoinlandsprodukt (BIP) pro Kopf**, **Alkoholkonsum**, **Übergewicht** und **Raucherprävalenz**. Ziel ist es, Muster zu erkennen und mögliche Korrelationen zwischen diesen Variablen und der Lebenserwartung zu identifizieren.

### Datenquellen und Überblick:

1. **WHO Life Expectancy at Birth (Years)**:
   - **Datenquelle:** Weltgesundheitsorganisation (WHO) - https://www.who.int/data/gho/data/indicators/indicator-details/GHO/life-expectancy-at-birth-(years) / blob:null/f8604b1b-a3cc-4cb7-93e6-577957c33777
   - **Daten:** Lebenserwartung bei der Geburt , aufgeteilt nach Geschlecht (männlich/weiblich).
   - **Zeitraum:** 2000 bis 2021.
   - **Format:** CSV

2. **GDP per capita, current prices**:
   - **Datenquelle:** Internationaler Währungsfonds (IWF) - https://www.imf.org/external/datamapper/NGDPDPC@WEO/OEMDC/ADVEC/WEOWORLD
   - **Daten:** BIP pro Kopf für verschiedene Länder.
   - **Zeitraum:** Ab 1980 bis 2024
   - **Format:** Excel

3. **WHO Alcohol Consumption (Recorded per capita, 15+, in litres of pure alcohol)**:
   - **Datenquelle:** Weltgesundheitsorganisation (WHO) - https://www.who.int/data/gho/data/indicators/indicator-details/GHO/alcohol-recorded-per-capita-(15-)-consumption-(in-litres-of-pure-alcohol) / blob:null/9c8e921d-4054-49e8-8a80-67fe22ded349
   - **Daten:** Aufgezeichneter Alkoholkonsum pro Kopf (ab 15 Jahren) in Litern reinem Alkohol.
   - **Zeitraum:** 1960 bis 2019.
   - **Format:** CSV

4. **WHO Prevalence of Obesity among Adults**:
   - **Datenquelle:** Weltgesundheitsorganisation (WHO) - https://www.who.int/data/gho/data/indicators/indicator-details/GHO/prevalence-of-obesity-among-adults-bmi-=-30-(age-standardized-estimate)-(-) / blob:null/2f4b0ec0-8723-49e6-8703-8c7093d448e0
   - **Daten:** Prävalenz von Übergewicht unter Erwachsenen (18+), aufgeteilt nach Geschlecht (m/w).
   - **Zeitraum:** 1990 bis 2021.
   - **Format:** CSV

5. **OECD Daily Smokers (15+)**:
   - **Datenquelle:** Organisation für wirtschaftliche Zusammenarbeit und Entwicklung (OECD) - https://www.oecd.org/en/data/indicators/daily-smokers.html?oecdcontrol-31056b3eeb-var6=_T%7CM%7CF&oecdcontrol-b84ba0ecd2-var3=2020
   - **Daten:** Anteil täglicher Raucher unter Erwachsenen (ab 15 Jahren) in OECD-Ländern.
   - **Zeitraum:** 1960 bis 2023 (Daten für jedes Jahr einzeln).
   - **Format:** CSV

Durch die Analyse dieser Daten wird es möglich sein, den Einfluss von ökonomischen und gesundheitlichen Faktoren auf die Lebenserwartung zu untersuchen und mögliche Trends und Zusammenhänge zu erkennen.

### Wahl der DB: MongoDB

Für dieses Projekt haben wir uns entschieden, **MongoDB** als Datenbanklösung zu verwenden, da es mehrere Vorteile bietet, die es ideal für die Verarbeitung großer und unterschiedlich strukturierter Datensätze machen. Hier sind die Hauptgründe, warum MongoDB eine hervorragende Wahl für unser Projekt ist:

1. **Flexible Datenstruktur (schemafrei)**  
   Die Daten, die wir verwenden, kommen in verschiedenen Formaten (z.B. CSV und Excel) und beinhalten unterschiedliche Arten von Informationen (Länder, Jahre, Geschlecht, etc.). MongoDB nutzt eine dokumentenorientierte Struktur, bei der die Daten in JSON-ähnlichen BSON-Dokumenten gespeichert werden. Diese Flexibilität ermöglicht es uns, verschiedene Datentypen und -strukturen ohne ein festes Schema zu integrieren, was besonders wichtig ist, wenn wir Daten aus unterschiedlichen Quellen zusammenführen.

2. **Skalierbarkeit und Performance**  
   MongoDB ist auf horizontale Skalierung ausgelegt und kann große Datenmengen effizient verarbeiten. Da wir mit „Big Data“ arbeiten, ist es wichtig, dass die Datenbank in der Lage ist, mit wachsendem Datenvolumen problemlos umzugehen, ohne dass die Performance leidet. MongoDB ermöglicht es, Daten auf mehrere Server zu verteilen, wodurch eine hohe Performance auch bei großen Datensätzen gewährleistet wird.

3. **Einfache Integration von CSV- und Excel-Daten**  
   MongoDB bietet eine einfache Möglichkeit, Daten aus CSV-Dateien zu importieren. Da ein großer Teil unserer Daten als CSV-Dateien vorliegt (z.B. WHO- und OECD-Daten), ist dies ein wichtiger Vorteil. Für Excel-Dateien können wir mit Python und Pandas die Daten einlesen und problemlos in MongoDB speichern.

4. **Aggregation und MapReduce**  
   MongoDB verfügt über ein leistungsstarkes Aggregations-Framework und unterstützt MapReduce-Operationen. Diese Funktionen sind besonders nützlich für die Durchführung komplexer Datenanalysen. Wir können Aggregationen für verschiedene Kennzahlen wie Lebenserwartung, BIP oder Übergewicht basierend auf Kriterien wie Jahr oder Geschlecht durchführen.

5. **Geografische und zeitliche Analyse**  
   Viele unserer Datensätze erfordern geografische Zuordnung und zeitliche Analysen, z.B. Lebenserwartung nach Land und Jahr. MongoDB unterstützt geospatiale Abfragen und Zeitstempel, was uns dabei hilft, regionale Trends und zeitabhängige Entwicklungen zu analysieren.

6. **Verfügbarkeit von MapReduce**  
   Da wir auch mit großen Datenmengen arbeiten, benötigen wir die Möglichkeit, komplexe Berechnungen über Jahre und Länder hinweg durchzuführen. MongoDB unterstützt MapReduce-Operationen, die uns helfen, parallele Berechnungen effizient auf großen Datensätzen durchzuführen.

Durch die Verwendung von **MongoDB** in Kombination mit Python-Bibliotheken wie **pymongo** können wir die Daten laden, Aggregationen durchführen und komplexe Datenanalysen auf einer skalierbaren Plattform durchführen.

### Docker-Infrastruktur

Die Infrastruktur besteht aus zwei Containern:

1. **MongoDB-Container** – für die Datenbank.

2. **Jupyter-Notebook-Container** – für die Python-Umgebung zur Analyse und Visualisierung.

Hier ist die docker-compose.yml-Datei, die die MongoDB-Instanz und den Jupyter-Notebook-Container definiert.

In [1]:
# version: '3.7'

# services:
#   mongodb:
#     image: mongo:latest
#     container_name: mongodb
#     ports:
#       - "27017:27017"  # MongoDB Standard-Port
#     volumes:
#       - ./data/db:/data/db  # Daten werden auf deinem lokalen System gespeichert
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=root
#       - MONGO_INITDB_ROOT_PASSWORD=example

#   jupyter:
#     image: jupyter/scipy-notebook:latest
#     container_name: jupyter-notebook
#     ports:
#       - "8888:8888"  # Jupyter Notebook-Standard-Port
#     volumes:
#       - ./notebooks:/home/jovyan/work  # Notebook-Daten werden auf deinem lokalen System gespeichert
#     environment:
#       - JUPYTER_TOKEN=mytoken  # Authentifizierungstoken für Jupyter Notebook
#     depends_on:
#       - mongodb

In [2]:
# Starten der Container
# docker-compose up -d

In [3]:
# Installation notwendiger Bibliotheken
!pip install pymongo pandas openpyxl matplotlib seaborn

Requirement already satisfied: pymongo in c:\python312\lib\site-packages (4.12.0)
Requirement already satisfied: pandas in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (2.2.3)
Requirement already satisfied: openpyxl in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (3.1.5)
Requirement already satisfied: matplotlib in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (3.10.1)
Requirement already satisfied: seaborn in c:\python312\lib\site-packages (0.13.2)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\python312\lib\site-packages (from pymongo) (2.7.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: et-xmlfile in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: six>=1.5 in c:\users\osm_loq\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
# Import von Bibliotheken
import pymongo
import pandas as pd

# Verbindung zur MongoDB
client = pymongo.MongoClient("mongodb://root:example@mongodb:27017/")
db = client['bigdata']
collection = db['life_expectancy']

# Laden der CSV-Dateien
df_life_expectancy = pd.read_csv("/home/jovyan/files/life_expectancy_at_birth_years.csv")
df_alcohol_per_capita = pd.read_csv("/home/jovyan/files/alcohol_recorded_per_capita_in_litres.csv")
df_prevalence_obesity = pd.read_csv("/home/jovyan/files/prevalence_of_obesity_among_adults.csv")

file_paths = [
    ("/home/jovyan/files/daily_smokers_2005.csv", 2005),
    ("/home/jovyan/files/daily_smokers_2010.csv", 2010),
    ("/home/jovyan/files/daily_smokers_2015.csv", 2015),
    ("/home/jovyan/files/daily_smokers_2020.csv", 2020)
]
dfs = []
for file_path, year in file_paths:
    df = pd.read_csv(file_path, skiprows=2, header=0, sep=';', decimal=',')
    df['Year'] = year
    dfs.append(df)
df_daily_smokers = pd.concat(dfs, ignore_index=True)

# Laden der Excel-Datei
df_gdp_per_capita = pd.read_excel("/home/jovyan/files/gpd_per_capita.xls")

# CSV-Daten in MongoDB importieren
data = df_life_expectancy.to_dict(orient='records')
collection.insert_many(data)

FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/files/life_expectancy_at_birth_years.csv'

In [16]:
# Abrufen der Daten aus der DB
data_from_db = collection.find()

# In DataFrame umwandeln
df_mongo = pd.DataFrame(list(data_from_db))

# Erste Zeilen des DataFrames anzeigen
df_mongo.head()

,_id,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,67e95b694b0bb6acc556d564,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,...,NaN,NaN,50.49,NaN,52.57,51.5 [50.5-52.6],NaN,NaN,EN,2024-08-01T22:00:00.000Z
1,67e95b694b0bb6acc556d565,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,...,NaN,NaN,51.06,NaN,53.36,52.3 [51.1-53.4],NaN,NaN,EN,2024-08-01T22:00:00.000Z
2,67e95b694b0bb6acc556d566,WHOSIS_000001,Life expectancy at birth (years),text,EMR,Eastern Mediterranean,Country,SOM,Somalia,Year,...,NaN,NaN,52.92,NaN,55.11,54.0 [52.9-55.1],NaN,NaN,EN,2024-08-01T22:00:00.000Z
3,67e95b694b0bb6acc556d567,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,SWZ,Eswatini,Year,...,NaN,NaN,53.49,NaN,55.87,54.6 [53.5-55.9],NaN,NaN,EN,2024-08-01T22:00:00.000Z
4,67e95b694b0bb6acc556d568,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,MOZ,Mozambique,Year,...,NaN,NaN,56.64,NaN,58.77,57.7 [56.6-58.8],NaN,NaN,EN,2024-08-01T22:00:00.000Z

In [17]:
# Anzeige der Lebenserwartung
df_life_expectancy.head()

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2021,...,NaN,NaN,50.49,NaN,52.57,51.5 [50.5-52.6],NaN,NaN,EN,2024-08-01T22:00:00.000Z
1,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2021,...,NaN,NaN,51.06,NaN,53.36,52.3 [51.1-53.4],NaN,NaN,EN,2024-08-01T22:00:00.000Z
2,WHOSIS_000001,Life expectancy at birth (years),text,EMR,Eastern Mediterranean,Country,SOM,Somalia,Year,2021,...,NaN,NaN,52.92,NaN,55.11,54.0 [52.9-55.1],NaN,NaN,EN,2024-08-01T22:00:00.000Z
3,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,SWZ,Eswatini,Year,2021,...,NaN,NaN,53.49,NaN,55.87,54.6 [53.5-55.9],NaN,NaN,EN,2024-08-01T22:00:00.000Z
4,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,MOZ,Mozambique,Year,2021,...,NaN,NaN,56.64,NaN,58.77,57.7 [56.6-58.8],NaN,NaN,EN,2024-08-01T22:00:00.000Z

In [18]:
# Anzeige des Alkoholkosnums
df_alcohol_per_capita.head()

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,SA_0000001400,"Alcohol, recorded per capita (15+) consumption...",numeric,EMR,Eastern Mediterranean,Country,AFG,Afghanistan,Year,2020,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2024-08-11T22:00:00.000Z
1,SA_0000001400,"Alcohol, recorded per capita (15+) consumption...",numeric,EMR,Eastern Mediterranean,Country,KWT,Kuwait,Year,2020,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2024-08-11T22:00:00.000Z
2,SA_0000001400,"Alcohol, recorded per capita (15+) consumption...",numeric,EMR,Eastern Mediterranean,Country,LBY,Libya,Year,2020,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2024-08-11T22:00:00.000Z
3,SA_0000001400,"Alcohol, recorded per capita (15+) consumption...",numeric,AFR,Africa,Country,MRT,Mauritania,Year,2020,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2024-08-11T22:00:00.000Z
4,SA_0000001400,"Alcohol, recorded per capita (15+) consumption...",numeric,EMR,Eastern Mediterranean,Country,PAK,Pakistan,Year,2020,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2024-08-11T22:00:00.000Z

In [19]:
# Anzeige übergewichtiger Personen
df_prevalence_obesity.head()

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,NCD_BMI_30A,"Prevalence of obesity among adults, BMI &Great...",numeric,AFR,Africa,Country,SEN,Senegal,Year,2022,...,NaN,NaN,8.01,NaN,12.59,10.2 [8.0-12.6],NaN,NaN,EN,2024-02-28T23:00:00.000Z
1,NCD_BMI_30A,"Prevalence of obesity among adults, BMI &Great...",numeric,AFR,Africa,Country,MOZ,Mozambique,Year,2022,...,NaN,NaN,7.93,NaN,12.97,10.3 [7.9-13.0],NaN,NaN,EN,2024-02-28T23:00:00.000Z
2,NCD_BMI_30A,"Prevalence of obesity among adults, BMI &Great...",numeric,SEAR,South-East Asia,Country,LKA,Sri Lanka,Year,2022,...,NaN,NaN,8.99,NaN,12.28,10.6 [9.0-12.3],NaN,NaN,EN,2024-02-28T23:00:00.000Z
3,NCD_BMI_30A,"Prevalence of obesity among adults, BMI &Great...",numeric,AMR,Americas,Country,HTI,Haiti,Year,2022,...,NaN,NaN,8.37,NaN,13.33,10.7 [8.4-13.3],NaN,NaN,EN,2024-02-28T23:00:00.000Z
4,NCD_BMI_30A,"Prevalence of obesity among adults, BMI &Great...",numeric,SEAR,South-East Asia,Country,PRK,Democratic People's Republic of Korea,Year,2022,...,NaN,NaN,5.64,NaN,17.52,10.8 [5.6-17.5],NaN,NaN,EN,2024-02-28T23:00:00.000Z

In [20]:
# Anzeige der täglichen Raucher
df_daily_smokers.head()

      Category  Total  Women   Men  Year
0       France   27.5   23.2  32.0  2005
1      Denmark   26.0   24.0  28.0  2005
2        Korea   25.9    4.7  47.3  2005
3  Netherlands   25.2   22.1  28.4  2005
4       Norway   25.0   24.0  26.0  2005

In [21]:
# Anzeige Bruttoinlandsprodukt
df_gdp_per_capita.head()

,"GDP per capita, current prices\n (U.S. dollars per capita)",1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,516.664,356.063,352.456,410.933,no data,no data,no data,no data,no data,no data
2,Albania,728.359,817.734,824.542,815.529,788.332,788.801,855.724,832.245,805.046,...,5353.303,6396.166,6870.21,8299.278,9598.191,10386.312,11211.431,11937.672,12713.803,13543.306
3,Algeria,2462.085,2502.13,2446.588,2514.256,2640.191,2988.545,2929.092,2935.816,2326.571,...,3757.585,4169.984,4981.822,5221.813,5579.128,5592.852,5645.511,5680.587,5705.771,5733.606
4,Andorra,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,36973.845,41806.876,41378.881,43809.726,45278.52,45994.879,46819.401,47330.444,47873.433,48458.183